# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get output files
        run: ls -d "$PWD/target/"*
      - name: Create staging directory
        run: mkdir staging && cp target/*.jar staging
      - name: Publish JAR
        uses: actions/upload-artifact@v2
        with:
          name: pikt
          path: staging/pikt.jar
