# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Create staging directory
        run: mkdir staging && mkdir staging/libraries
      - name: Copy JARs
        run: |
          rm -rf */target/*-without-dependencies.jar
          cp */target/*.jar staging
          mv staging/*lib.jar staging/libraries
      - name: Run welcome command
        run: |
          cd staging
          java -jar pikt.jar welcome
      - name: Get output files
        run: ls -d "$PWD/staging/"*
      - name: Publish JAR
        uses: actions/upload-artifact@v4
        with:
          name: pikt
          path: staging
